### ISSUE TITLE
More tags

### ISSUE THREAD

**Issue by iamraghavgupta** [PathriK/GaanaExtractor#10]
The api provides "genre" and "artists" tag too. They can also be added to make the resulting songs include that, so in apps then display songs by artists by  default doesn't show it as unknown artist.
this can be another enhancement.
Since multiple artists are there, that has to be taken into account.

**Comment by PathriK** [comment]
@iamraghavgupta , can you try once with the latest binary GaanaExtractor-2.0-SNAPSHOT.jar to see if the fix is fine?

Thanks
