### ISSUE TITLE
Files with same track title

### ISSUE THREAD

**Issue by iamraghavgupta** [PathriK/GaanaExtractor#11]
Currently, it overwrites the file and we get only a single file.
Since only the title is name, but it a different version of the song, there must be an option like it puts a number etc. so as to keep both the files.

**Comment by PathriK** [comment]
Any sample files? Just file ids should be fine to work with.

**Comment by iamraghavgupta** [comment]
71303  //  71304
this is one example.... there are many others

**Comment by PathriK** [comment]
I am thinking of using the seokey to build the file names. That way files names have to be unique. What do u think??

**Comment by iamraghavgupta** [comment]
yes, that would be better for multiple names, but still if we look into, for some songs, the title is better for the song, than the corresponding seokey. that might result in a name that is not easily recognizable.

I will try running seokey for title, and see if that can help. I have around 500 files, so results can provide good information

**Comment by PathriK** [comment]
@iamraghavgupta , can you try once with the binary GaanaExtractor-2.0-SNAPSHOT.jar to see if the fix is fine?

Thanks

**Comment by iamraghavgupta** [comment]
Opened a new issue..
