### ISSUE TITLE
 error in reading files

### ISSUE THREAD

**Issue by iamraghavgupta** [PathriK/GaanaExtractor#12]
Some files result in reading error
[GaanaExtractor.txt](https://github.com/PathriK/GaanaExtractor/files/574752/GaanaExtractor.txt)
![untitled](https://cloud.githubusercontent.com/assets/9131957/20050692/c15fe68e-a4f0-11e6-9d89-a7ad14d67d11.png)

**Comment by PathriK** [comment]
Need to check the the file type that is getting downloaded. File type is found using the methods in the following class.
https://bitbucket.org/ijabz/jaudiotagger/src/833d74948ec612cffd5b70683dda209ef5ba97c2/src/org/jaudiotagger/utils/FileTypeUtil.java?fileviewer=file-view-default

**Comment by PathriK** [comment]
Need to update jaudiotagger with file signatures from below site:
www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=687&strPageToDisplay=signatures

**Comment by PathriK** [comment]
Have raised a pull request to @ijabz
https://bitbucket.org/ijabz/jaudiotagger/pull-requests/45/file-type-signature-updates

Will build a new version once the pull request has been merged by him

**Comment by PathriK** [comment]
Have hosted a snapshot version in the following URL:

https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/in/pathri/gaana/GaanaExtractor/2.0-SNAPSHOT/GaanaExtractor-2.0-20161123.152810-1.jar

Please try out and see if the reported error is fixed. 

Thanks
