### ISSUE TITLE
Conversion for few files are failing because of new line character in track title

### ISSUE THREAD

**Issue by PathriK** [PathriK/GaanaExtractor#15]
Need to analyse and see if there are any other invalid characters in track title. 

This issue is raised OBO @Gkr001.

Log File:
[GaanaExtractor_Aakash.log.txt](https://github.com/PathriK/GaanaExtractor/files/628992/GaanaExtractor_Aakash.log.txt)

**Comment by PathriK** [comment]
Space in Album name also causing conversion error. That also will be fixed as part of this issue

**Comment by Gkr001** [comment]
Thanks for the great work. If there's anything to be tested, just update here. Cheers!
