### ISSUE TITLE
Not working for all downloaded songs

### ISSUE THREAD

**Issue by SaiAvinash92** [PathriK/GaanaExtractor#2]
Hey bro, I tried downloading the first 6 songs of US top 50 playlist but after the whole process I only have one song in the converted folder also tried some Hindi songs but this process is not working, I'm getting no converted folder after running the command. Can you help me with the issue 
Also, can you provide the Linux commands for the process?

**Comment by PathriK** [comment]
R u getting any error while trying to convert?  If so can u post the error here? 
Also If u could mention the names of some songs that didn't get converted, I can try it from my end and check.

**Comment by SaiAvinash92** [comment]
Yeah sure
Download the top 6 songs from here - http://gaana.com/topcharts/gaana-dj-us-top-50
try converting them, only the first song(cheerleader) will get converted and the rest don't. Tried some tamil, hindi songs too, unfortunately only one song out of 5 gets converted. Hope you fix this soon :D

**Comment by SaiAvinash92** [comment]
Also it would be nice if all the songs in converted folder be in a single folder rather that creating folders for every artist. If all songs are in same folder it would be easy to copy or arrange the songs.. 
If you need any testing to do or something else, ping me :)

**Comment by PathriK** [comment]
@SaiAvinash92 : Please ping me in hangouts.Lets discuss tomorrow :) My mail id : pathrikumark@gmail.com.

**Comment by PathriK** [comment]
Release 1.2 must have fixed the issue. Please check and let me know when possible.
Thanks

**Comment by PathriK** [comment]
Hi
After a long time have released a new version....
https://github.com/PathriK/GaanaExtractor/releases/tag/v2.0-BETA
Now it should be able to convert nearly all the songs..
Please try it out and let me know if the issues are fixed..
