### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FahadSalim** [PathriK/GaanaExtractor#3]
![error gaana](https://cloud.githubusercontent.com/assets/13642679/9060752/a8db0440-3a84-11e5-8193-0799754b5870.jpg)

I changed the slashes but I was still getting some error. All I can read is something like file not found.

**Comment by PathriK** [comment]
Strange, I tried using batches of 10 and seems to be working. Anyway, will fix it this weekend and let u know so that you can try it. Fingers crossed :)

**Comment by PathriK** [comment]
@FahadSalim Please try the v1.1 and let me know whether it works.

**Comment by FahadSalim** [comment]
![error gaana](https://cloud.githubusercontent.com/assets/13642679/9096214/c6609b46-3b89-11e5-9058-da0e3da447fc.jpg)
I can see it looking for info but I can't find any converted folder. I am uploading the files, I'll send you the link as soon as its done.

**Comment by PathriK** [comment]
From the error displayed, the only guess I could make is that there is no data in Gaana server for a particular song. Will confirm once I get ur uploaded songs. U can send it to my gmail.

**Comment by PathriK** [comment]
Possible for you to send me the complete contents of the command prompt when u run the jar? That might be enough to pin point the issue.

Even the names(integer numbers) of all the files should be sufficient to find the issue.

**Comment by FahadSalim** [comment]
https://drive.google.com/file/d/0BwcUZtuHRu4lMjhhU1dGb3dZb2c/view?usp=sharing

these are my songs. i will upload the screenshots of the whole process soon

**Comment by FahadSalim** [comment]
![error gaana 0](https://cloud.githubusercontent.com/assets/13642679/9266398/a11b3798-420e-11e5-930e-445a9664c8b2.jpg)
![error gaana 1](https://cloud.githubusercontent.com/assets/13642679/9266397/a11ab502-420e-11e5-9b4d-52f2c8975669.jpg)
![error gaana 2](https://cloud.githubusercontent.com/assets/13642679/9266399/a11ff378-420e-11e5-8461-5d9b886b9caf.jpg)
![error gaana 3](https://cloud.githubusercontent.com/assets/13642679/9266400/a11fee14-420e-11e5-981f-76de183aff6e.jpg)

**Comment by PathriK** [comment]
Possible for u to ping me in hangouts or gitter (link in readme of the repo)???

**Comment by FahadSalim** [comment]
I would love to but I am a bit busy in a family emergency these days.

**Comment by PathriK** [comment]
okie..nps...I guess the error is because some files info are not there in the Gaana Server. Will let u know of any updates regarding this in the next version. Thanks for your time and work :)

**Comment by PathriK** [comment]
Release 1.2 must have fixed the issue. Please check and let me know when possible.
Thanks

**Comment by PathriK** [comment]
Hi
After a long time have released a new version....
https://github.com/PathriK/GaanaExtractor/releases/tag/v2.0-BETA
Now it should be able to convert nearly all the songs..
Please try it out and let me know if the issues are fixed..
