### ISSUE TITLE
Files are not converting

### ISSUE THREAD

**Issue by reddytech** [PathriK/GaanaExtractor#5]
Exception in thread "main" org.jaudiotagger.tag.KeyNotFoundException: Invalid field URL_LYRICS_SITE for ID3v1 tag

**Comment by PathriK** [comment]
Hi
After a long time have released a new version....
https://github.com/PathriK/GaanaExtractor/releases/tag/v2.0-BETA
Now it should be able to convert nearly all the songs..
Please try it out and let me know if the issues are fixed..
