### ISSUE TITLE
unable to extract jar file

### ISSUE THREAD

**Issue by paras03** [PathriK/GaanaExtractor#7]
I have downloaded latest file, followed the instuction, tried to run the command prompt, but then it throws message , unable to exttract jar file

can you help me 

Thanks

Paras

**Comment by PathriK** [comment]
Hi,
Thanks for trying out my app. Kindly send me a screen shot of the error
message with the detail steps u followed so that I can better understand
the issue
Thanks
Keerthi kumar p

**Comment by paras03** [comment]
Thanks,  ok I will

**Comment by paras03** [comment]
By end of the day
