### ISSUE TITLE
NullPointer Exception while extracting a few files

### ISSUE THREAD

**Issue by iamraghavgupta** [PathriK/GaanaExtractor#9]
![untitled](https://cloud.githubusercontent.com/assets/9131957/20027482/32b77214-a33b-11e6-951f-d74477ca0a24.png)

**Comment by iamraghavgupta** [comment]
The file is 1199218.
The API results in:
{"tracks":null,"count":0,"status":1,"user-token-status":0,"user_token_status":0}
when accessed.

**Comment by iamraghavgupta** [comment]
[GaanaExtractor.txt](https://github.com/PathriK/GaanaExtractor/files/573014/GaanaExtractor.txt)

**Comment by PathriK** [comment]
@iamraghavgupta , can you try once with the binary GaanaExtractor-2.0-SNAPSHOT.jar to see if the fix is fine?

Thanks

**Comment by iamraghavgupta** [comment]
Created a new issue..
